version: "3.9"  # optional since v1.27.0
services:
   web:
       container_name: django_impression
       build: .
       command: python manage.py runserver localhost:8000
       volumes:
         - .:app
       ports:
           - "8000:8000"
