# Generated by Django 4.0.4 on 2022-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='base_avatar.png', upload_to='static/images/avatars', verbose_name='Фото'),
        ),
    ]
