# Generated by Django 4.0.4 on 2022-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
