# Generated by Django 4.0.4 on 2022-04-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0006_remove_impression_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
