# Generated by Django 4.0.4 on 2022-04-28 15:31

from django.db import migrations
import django.utils.timezone
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0007_impression_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.utils.timezone.now, max_length=63, verbose_name='Локация'),
            preserve_default=False,
        ),
    ]
