# Generated by Django 4.0.4 on 2022-04-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0009_remove_impression_lat_remove_impression_lon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='address',
        ),
    ]
