# Generated by Django 4.0.4 on 2022-04-28 18:34

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0010_remove_impression_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='56.00637898153531,92.86683082580566', max_length=63),
        ),
    ]
