# Generated by Django 4.0.4 on 2022-04-30 05:37

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('impression_storage', '0012_impression_address_alter_impression_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impression',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='', max_length=63, verbose_name='Координаты'),
        ),
    ]
