name: Start unit tests

on:
    push: 
    pull_request:

jobs:
    build:
    
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8, 3.9]
        
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Flake8
              run: |
                  flake8

            - name: Coverage report
              run: |
                  cd PlaceRemember
                  coverage run manage.py test
                  coverage report

            - name: Run Tests
              run: |
                  cd PlaceRemember
                  python manage.py test
                  
            - name: Upload coverage data to coveralls.io
              run: |
                  cd PlaceRemember
                  coveralls
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COVERALLS_SERVICE_NAME: github